// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: trip/trip.proto

package trip

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripService_CreateTrip_FullMethodName                = "/trip.TripService/CreateTrip"
	TripService_SubmitBidOrOffer_FullMethodName          = "/trip.TripService/SubmitBidOrOffer"
	TripService_AcceptOffer_FullMethodName               = "/trip.TripService/AcceptOffer"
	TripService_CounterOffer_FullMethodName              = "/trip.TripService/CounterOffer"
	TripService_GetTrip_FullMethodName                   = "/trip.TripService/GetTrip"
	TripService_GetActiveTrips_FullMethodName            = "/trip.TripService/GetActiveTrips"
	TripService_GetActiveTripsByRider_FullMethodName     = "/trip.TripService/GetActiveTripsByRider"
	TripService_AcceptTrip_FullMethodName                = "/trip.TripService/AcceptTrip"
	TripService_CancelTrip_FullMethodName                = "/trip.TripService/CancelTrip"
	TripService_CompleteTrip_FullMethodName              = "/trip.TripService/CompleteTrip"
	TripService_GetBiddingSession_FullMethodName         = "/trip.TripService/GetBiddingSession"
	TripService_GetBiddingSessionsByRider_FullMethodName = "/trip.TripService/GetBiddingSessionsByRider"
	TripService_GetBidRankings_FullMethodName            = "/trip.TripService/GetBidRankings"
	TripService_InstantMatch_FullMethodName              = "/trip.TripService/InstantMatch"
	TripService_GetInstantMatchStatus_FullMethodName     = "/trip.TripService/GetInstantMatchStatus"
	TripService_CancelInstantMatch_FullMethodName        = "/trip.TripService/CancelInstantMatch"
	TripService_InstantAccept_FullMethodName             = "/trip.TripService/InstantAccept"
	TripService_GetTripHistory_FullMethodName            = "/trip.TripService/GetTripHistory"
	TripService_GetTripHistoryByRider_FullMethodName     = "/trip.TripService/GetTripHistoryByRider"
	TripService_GetTripHistoryByDriver_FullMethodName    = "/trip.TripService/GetTripHistoryByDriver"
	TripService_IsTripActive_FullMethodName              = "/trip.TripService/IsTripActive"
	TripService_CreateRating_FullMethodName              = "/trip.TripService/CreateRating"
	TripService_GetRating_FullMethodName                 = "/trip.TripService/GetRating"
	TripService_ListRating_FullMethodName                = "/trip.TripService/ListRating"
	TripService_DeleteRating_FullMethodName              = "/trip.TripService/DeleteRating"
	TripService_UpdateRating_FullMethodName              = "/trip.TripService/UpdateRating"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	// Trips
	CreateTrip(ctx context.Context, in *TripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	SubmitBidOrOffer(ctx context.Context, in *BidOrOfferRequest, opts ...grpc.CallOption) (*BidOrOfferResponse, error)
	AcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*AcceptOfferResponse, error)
	CounterOffer(ctx context.Context, in *CounterOfferRequest, opts ...grpc.CallOption) (*CounterOfferResponse, error)
	GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*GetTripResponse, error)
	GetActiveTrips(ctx context.Context, in *GetActiveTripsRequest, opts ...grpc.CallOption) (*GetActiveTripsResponse, error)
	GetActiveTripsByRider(ctx context.Context, in *GetActiveTripsByRiderRequest, opts ...grpc.CallOption) (*GetActiveTripsByRiderResponse, error)
	AcceptTrip(ctx context.Context, in *AcceptTripRequest, opts ...grpc.CallOption) (*AcceptTripResponse, error)
	CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*CancelTripResponse, error)
	CompleteTrip(ctx context.Context, in *CompleteTripRequest, opts ...grpc.CallOption) (*CompleteTripResponse, error)
	// Bidding Session
	GetBiddingSession(ctx context.Context, in *GetBiddingSessionRequest, opts ...grpc.CallOption) (*GetBiddingSessionResponse, error)
	GetBiddingSessionsByRider(ctx context.Context, in *GetBiddingSessionsByRiderRequest, opts ...grpc.CallOption) (*GetBiddingSessionsByRiderResponse, error)
	GetBidRankings(ctx context.Context, in *GetBidRankingsRequest, opts ...grpc.CallOption) (*GetBidRankingsResponse, error)
	// Instant Match
	InstantMatch(ctx context.Context, in *InstantMatchRequest, opts ...grpc.CallOption) (*InstantMatchResponse, error)
	GetInstantMatchStatus(ctx context.Context, in *GetInstantMatchStatusRequest, opts ...grpc.CallOption) (*GetInstantMatchStatusResponse, error)
	CancelInstantMatch(ctx context.Context, in *CancelInstantMatchRequest, opts ...grpc.CallOption) (*CancelInstantMatchResponse, error)
	InstantAccept(ctx context.Context, in *InstantAcceptRequest, opts ...grpc.CallOption) (*InstantAcceptResponse, error)
	//Trip History
	GetTripHistory(ctx context.Context, in *TripHistoryFilterRequest, opts ...grpc.CallOption) (*TripHistoryResponse, error)
	GetTripHistoryByRider(ctx context.Context, in *GetTripHistoryByRiderRequest, opts ...grpc.CallOption) (*GetTripHistoryResponse, error)
	GetTripHistoryByDriver(ctx context.Context, in *GetTripHistoryByDriverRequest, opts ...grpc.CallOption) (*GetTripHistoryResponse, error)
	IsTripActive(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
	//Rating
	CreateRating(ctx context.Context, in *RatingRequest, opts ...grpc.CallOption) (*RatingResponse, error)
	GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error)
	ListRating(ctx context.Context, in *ListRatingRequest, opts ...grpc.CallOption) (*ListRatingResponse, error)
	DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*DeleteRatingResponse, error)
	UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) CreateTrip(ctx context.Context, in *TripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) SubmitBidOrOffer(ctx context.Context, in *BidOrOfferRequest, opts ...grpc.CallOption) (*BidOrOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidOrOfferResponse)
	err := c.cc.Invoke(ctx, TripService_SubmitBidOrOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*AcceptOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptOfferResponse)
	err := c.cc.Invoke(ctx, TripService_AcceptOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CounterOffer(ctx context.Context, in *CounterOfferRequest, opts ...grpc.CallOption) (*CounterOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CounterOfferResponse)
	err := c.cc.Invoke(ctx, TripService_CounterOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*GetTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripResponse)
	err := c.cc.Invoke(ctx, TripService_GetTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTrips(ctx context.Context, in *GetActiveTripsRequest, opts ...grpc.CallOption) (*GetActiveTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveTripsResponse)
	err := c.cc.Invoke(ctx, TripService_GetActiveTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTripsByRider(ctx context.Context, in *GetActiveTripsByRiderRequest, opts ...grpc.CallOption) (*GetActiveTripsByRiderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveTripsByRiderResponse)
	err := c.cc.Invoke(ctx, TripService_GetActiveTripsByRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AcceptTrip(ctx context.Context, in *AcceptTripRequest, opts ...grpc.CallOption) (*AcceptTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptTripResponse)
	err := c.cc.Invoke(ctx, TripService_AcceptTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*CancelTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTripResponse)
	err := c.cc.Invoke(ctx, TripService_CancelTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CompleteTrip(ctx context.Context, in *CompleteTripRequest, opts ...grpc.CallOption) (*CompleteTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTripResponse)
	err := c.cc.Invoke(ctx, TripService_CompleteTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBiddingSession(ctx context.Context, in *GetBiddingSessionRequest, opts ...grpc.CallOption) (*GetBiddingSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBiddingSessionResponse)
	err := c.cc.Invoke(ctx, TripService_GetBiddingSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBiddingSessionsByRider(ctx context.Context, in *GetBiddingSessionsByRiderRequest, opts ...grpc.CallOption) (*GetBiddingSessionsByRiderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBiddingSessionsByRiderResponse)
	err := c.cc.Invoke(ctx, TripService_GetBiddingSessionsByRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetBidRankings(ctx context.Context, in *GetBidRankingsRequest, opts ...grpc.CallOption) (*GetBidRankingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBidRankingsResponse)
	err := c.cc.Invoke(ctx, TripService_GetBidRankings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) InstantMatch(ctx context.Context, in *InstantMatchRequest, opts ...grpc.CallOption) (*InstantMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstantMatchResponse)
	err := c.cc.Invoke(ctx, TripService_InstantMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetInstantMatchStatus(ctx context.Context, in *GetInstantMatchStatusRequest, opts ...grpc.CallOption) (*GetInstantMatchStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstantMatchStatusResponse)
	err := c.cc.Invoke(ctx, TripService_GetInstantMatchStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelInstantMatch(ctx context.Context, in *CancelInstantMatchRequest, opts ...grpc.CallOption) (*CancelInstantMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInstantMatchResponse)
	err := c.cc.Invoke(ctx, TripService_CancelInstantMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) InstantAccept(ctx context.Context, in *InstantAcceptRequest, opts ...grpc.CallOption) (*InstantAcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstantAcceptResponse)
	err := c.cc.Invoke(ctx, TripService_InstantAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripHistory(ctx context.Context, in *TripHistoryFilterRequest, opts ...grpc.CallOption) (*TripHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripHistoryResponse)
	err := c.cc.Invoke(ctx, TripService_GetTripHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripHistoryByRider(ctx context.Context, in *GetTripHistoryByRiderRequest, opts ...grpc.CallOption) (*GetTripHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripHistoryResponse)
	err := c.cc.Invoke(ctx, TripService_GetTripHistoryByRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripHistoryByDriver(ctx context.Context, in *GetTripHistoryByDriverRequest, opts ...grpc.CallOption) (*GetTripHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripHistoryResponse)
	err := c.cc.Invoke(ctx, TripService_GetTripHistoryByDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) IsTripActive(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, TripService_IsTripActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CreateRating(ctx context.Context, in *RatingRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, TripService_CreateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, TripService_GetRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListRating(ctx context.Context, in *ListRatingRequest, opts ...grpc.CallOption) (*ListRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRatingResponse)
	err := c.cc.Invoke(ctx, TripService_ListRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*DeleteRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRatingResponse)
	err := c.cc.Invoke(ctx, TripService_DeleteRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*RatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResponse)
	err := c.cc.Invoke(ctx, TripService_UpdateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility.
type TripServiceServer interface {
	// Trips
	CreateTrip(context.Context, *TripRequest) (*TripResponse, error)
	SubmitBidOrOffer(context.Context, *BidOrOfferRequest) (*BidOrOfferResponse, error)
	AcceptOffer(context.Context, *AcceptOfferRequest) (*AcceptOfferResponse, error)
	CounterOffer(context.Context, *CounterOfferRequest) (*CounterOfferResponse, error)
	GetTrip(context.Context, *GetTripRequest) (*GetTripResponse, error)
	GetActiveTrips(context.Context, *GetActiveTripsRequest) (*GetActiveTripsResponse, error)
	GetActiveTripsByRider(context.Context, *GetActiveTripsByRiderRequest) (*GetActiveTripsByRiderResponse, error)
	AcceptTrip(context.Context, *AcceptTripRequest) (*AcceptTripResponse, error)
	CancelTrip(context.Context, *CancelTripRequest) (*CancelTripResponse, error)
	CompleteTrip(context.Context, *CompleteTripRequest) (*CompleteTripResponse, error)
	// Bidding Session
	GetBiddingSession(context.Context, *GetBiddingSessionRequest) (*GetBiddingSessionResponse, error)
	GetBiddingSessionsByRider(context.Context, *GetBiddingSessionsByRiderRequest) (*GetBiddingSessionsByRiderResponse, error)
	GetBidRankings(context.Context, *GetBidRankingsRequest) (*GetBidRankingsResponse, error)
	// Instant Match
	InstantMatch(context.Context, *InstantMatchRequest) (*InstantMatchResponse, error)
	GetInstantMatchStatus(context.Context, *GetInstantMatchStatusRequest) (*GetInstantMatchStatusResponse, error)
	CancelInstantMatch(context.Context, *CancelInstantMatchRequest) (*CancelInstantMatchResponse, error)
	InstantAccept(context.Context, *InstantAcceptRequest) (*InstantAcceptResponse, error)
	//Trip History
	GetTripHistory(context.Context, *TripHistoryFilterRequest) (*TripHistoryResponse, error)
	GetTripHistoryByRider(context.Context, *GetTripHistoryByRiderRequest) (*GetTripHistoryResponse, error)
	GetTripHistoryByDriver(context.Context, *GetTripHistoryByDriverRequest) (*GetTripHistoryResponse, error)
	IsTripActive(context.Context, *GetTripRequest) (*TripResponse, error)
	//Rating
	CreateRating(context.Context, *RatingRequest) (*RatingResponse, error)
	GetRating(context.Context, *GetRatingRequest) (*RatingResponse, error)
	ListRating(context.Context, *ListRatingRequest) (*ListRatingResponse, error)
	DeleteRating(context.Context, *DeleteRatingRequest) (*DeleteRatingResponse, error)
	UpdateRating(context.Context, *UpdateRatingRequest) (*RatingResponse, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripServiceServer struct{}

func (UnimplementedTripServiceServer) CreateTrip(context.Context, *TripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTripServiceServer) SubmitBidOrOffer(context.Context, *BidOrOfferRequest) (*BidOrOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBidOrOffer not implemented")
}
func (UnimplementedTripServiceServer) AcceptOffer(context.Context, *AcceptOfferRequest) (*AcceptOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptOffer not implemented")
}
func (UnimplementedTripServiceServer) CounterOffer(context.Context, *CounterOfferRequest) (*CounterOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CounterOffer not implemented")
}
func (UnimplementedTripServiceServer) GetTrip(context.Context, *GetTripRequest) (*GetTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTrips(context.Context, *GetActiveTripsRequest) (*GetActiveTripsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTrips not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTripsByRider(context.Context, *GetActiveTripsByRiderRequest) (*GetActiveTripsByRiderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTripsByRider not implemented")
}
func (UnimplementedTripServiceServer) AcceptTrip(context.Context, *AcceptTripRequest) (*AcceptTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptTrip not implemented")
}
func (UnimplementedTripServiceServer) CancelTrip(context.Context, *CancelTripRequest) (*CancelTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedTripServiceServer) CompleteTrip(context.Context, *CompleteTripRequest) (*CompleteTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTrip not implemented")
}
func (UnimplementedTripServiceServer) GetBiddingSession(context.Context, *GetBiddingSessionRequest) (*GetBiddingSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBiddingSession not implemented")
}
func (UnimplementedTripServiceServer) GetBiddingSessionsByRider(context.Context, *GetBiddingSessionsByRiderRequest) (*GetBiddingSessionsByRiderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBiddingSessionsByRider not implemented")
}
func (UnimplementedTripServiceServer) GetBidRankings(context.Context, *GetBidRankingsRequest) (*GetBidRankingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBidRankings not implemented")
}
func (UnimplementedTripServiceServer) InstantMatch(context.Context, *InstantMatchRequest) (*InstantMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstantMatch not implemented")
}
func (UnimplementedTripServiceServer) GetInstantMatchStatus(context.Context, *GetInstantMatchStatusRequest) (*GetInstantMatchStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstantMatchStatus not implemented")
}
func (UnimplementedTripServiceServer) CancelInstantMatch(context.Context, *CancelInstantMatchRequest) (*CancelInstantMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInstantMatch not implemented")
}
func (UnimplementedTripServiceServer) InstantAccept(context.Context, *InstantAcceptRequest) (*InstantAcceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstantAccept not implemented")
}
func (UnimplementedTripServiceServer) GetTripHistory(context.Context, *TripHistoryFilterRequest) (*TripHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripHistory not implemented")
}
func (UnimplementedTripServiceServer) GetTripHistoryByRider(context.Context, *GetTripHistoryByRiderRequest) (*GetTripHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripHistoryByRider not implemented")
}
func (UnimplementedTripServiceServer) GetTripHistoryByDriver(context.Context, *GetTripHistoryByDriverRequest) (*GetTripHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTripHistoryByDriver not implemented")
}
func (UnimplementedTripServiceServer) IsTripActive(context.Context, *GetTripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsTripActive not implemented")
}
func (UnimplementedTripServiceServer) CreateRating(context.Context, *RatingRequest) (*RatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRating not implemented")
}
func (UnimplementedTripServiceServer) GetRating(context.Context, *GetRatingRequest) (*RatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRating not implemented")
}
func (UnimplementedTripServiceServer) ListRating(context.Context, *ListRatingRequest) (*ListRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRating not implemented")
}
func (UnimplementedTripServiceServer) DeleteRating(context.Context, *DeleteRatingRequest) (*DeleteRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRating not implemented")
}
func (UnimplementedTripServiceServer) UpdateRating(context.Context, *UpdateRatingRequest) (*RatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRating not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}
func (UnimplementedTripServiceServer) testEmbeddedByValue()                     {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	// If the following call panics, it indicates UnimplementedTripServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateTrip(ctx, req.(*TripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_SubmitBidOrOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidOrOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).SubmitBidOrOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_SubmitBidOrOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).SubmitBidOrOffer(ctx, req.(*BidOrOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptOffer(ctx, req.(*AcceptOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CounterOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CounterOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CounterOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CounterOffer(ctx, req.(*CounterOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTrip(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTrips(ctx, req.(*GetActiveTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTripsByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTripsByRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTripsByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTripsByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTripsByRider(ctx, req.(*GetActiveTripsByRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AcceptTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptTrip(ctx, req.(*AcceptTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CompleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CompleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CompleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CompleteTrip(ctx, req.(*CompleteTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBiddingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBiddingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBiddingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBiddingSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBiddingSession(ctx, req.(*GetBiddingSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBiddingSessionsByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBiddingSessionsByRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBiddingSessionsByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBiddingSessionsByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBiddingSessionsByRider(ctx, req.(*GetBiddingSessionsByRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetBidRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBidRankingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetBidRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetBidRankings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetBidRankings(ctx, req.(*GetBidRankingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_InstantMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).InstantMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_InstantMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).InstantMatch(ctx, req.(*InstantMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetInstantMatchStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstantMatchStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetInstantMatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetInstantMatchStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetInstantMatchStatus(ctx, req.(*GetInstantMatchStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelInstantMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInstantMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelInstantMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelInstantMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelInstantMatch(ctx, req.(*CancelInstantMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_InstantAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantAcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).InstantAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_InstantAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).InstantAccept(ctx, req.(*InstantAcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripHistoryFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripHistory(ctx, req.(*TripHistoryFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripHistoryByRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripHistoryByRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripHistoryByRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripHistoryByRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripHistoryByRider(ctx, req.(*GetTripHistoryByRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripHistoryByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripHistoryByDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripHistoryByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripHistoryByDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripHistoryByDriver(ctx, req.(*GetTripHistoryByDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_IsTripActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).IsTripActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_IsTripActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).IsTripActive(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CreateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateRating(ctx, req.(*RatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetRating(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListRating(ctx, req.(*ListRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_DeleteRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).DeleteRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_DeleteRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).DeleteRating(ctx, req.(*DeleteRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_UpdateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).UpdateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_UpdateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).UpdateRating(ctx, req.(*UpdateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TripService_CreateTrip_Handler,
		},
		{
			MethodName: "SubmitBidOrOffer",
			Handler:    _TripService_SubmitBidOrOffer_Handler,
		},
		{
			MethodName: "AcceptOffer",
			Handler:    _TripService_AcceptOffer_Handler,
		},
		{
			MethodName: "CounterOffer",
			Handler:    _TripService_CounterOffer_Handler,
		},
		{
			MethodName: "GetTrip",
			Handler:    _TripService_GetTrip_Handler,
		},
		{
			MethodName: "GetActiveTrips",
			Handler:    _TripService_GetActiveTrips_Handler,
		},
		{
			MethodName: "GetActiveTripsByRider",
			Handler:    _TripService_GetActiveTripsByRider_Handler,
		},
		{
			MethodName: "AcceptTrip",
			Handler:    _TripService_AcceptTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _TripService_CancelTrip_Handler,
		},
		{
			MethodName: "CompleteTrip",
			Handler:    _TripService_CompleteTrip_Handler,
		},
		{
			MethodName: "GetBiddingSession",
			Handler:    _TripService_GetBiddingSession_Handler,
		},
		{
			MethodName: "GetBiddingSessionsByRider",
			Handler:    _TripService_GetBiddingSessionsByRider_Handler,
		},
		{
			MethodName: "GetBidRankings",
			Handler:    _TripService_GetBidRankings_Handler,
		},
		{
			MethodName: "InstantMatch",
			Handler:    _TripService_InstantMatch_Handler,
		},
		{
			MethodName: "GetInstantMatchStatus",
			Handler:    _TripService_GetInstantMatchStatus_Handler,
		},
		{
			MethodName: "CancelInstantMatch",
			Handler:    _TripService_CancelInstantMatch_Handler,
		},
		{
			MethodName: "InstantAccept",
			Handler:    _TripService_InstantAccept_Handler,
		},
		{
			MethodName: "GetTripHistory",
			Handler:    _TripService_GetTripHistory_Handler,
		},
		{
			MethodName: "GetTripHistoryByRider",
			Handler:    _TripService_GetTripHistoryByRider_Handler,
		},
		{
			MethodName: "GetTripHistoryByDriver",
			Handler:    _TripService_GetTripHistoryByDriver_Handler,
		},
		{
			MethodName: "IsTripActive",
			Handler:    _TripService_IsTripActive_Handler,
		},
		{
			MethodName: "CreateRating",
			Handler:    _TripService_CreateRating_Handler,
		},
		{
			MethodName: "GetRating",
			Handler:    _TripService_GetRating_Handler,
		},
		{
			MethodName: "ListRating",
			Handler:    _TripService_ListRating_Handler,
		},
		{
			MethodName: "DeleteRating",
			Handler:    _TripService_DeleteRating_Handler,
		},
		{
			MethodName: "UpdateRating",
			Handler:    _TripService_UpdateRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip/trip.proto",
}
